/**
 * MODULE 2: LENDER PROGRAMS DATABASE
 * Hardcoded lender specifications from official 2025 rate sheets
 * TD, Santander, and Scotia Dealer Advantage
 */

import { LenderProgram, LenderType } from '../types/types';

const LENDER_PROGRAMS: Record<string, Record<string, LenderProgram>> = {
  TD: {
    '2-Key': {
      lender: 'TD',
      tier: '2-Key',
      rate: 11.99,
      ltv: 140,
      maxDsr: 50,
      minIncome: 1800,
      reserve: 300,
      fee: 799,
      negativeEquityLimit: 5000,
    },
    '3-Key': {
      lender: 'TD',
      tier: '3-Key',
      rate: 13.49,
      ltv: 140,
      maxDsr: 50,
      minIncome: 1800,
      reserve: 550,
      fee: 799,
      negativeEquityLimit: 5000,
    },
    '4-Key': {
      lender: 'TD',
      tier: '4-Key',
      rate: 15.99,
      ltv: 140,
      maxDsr: 50,
      minIncome: 1800,
      reserve: 600,
      fee: 799,
      negativeEquityLimit: 5000,
    },
    '5-Key': {
      lender: 'TD',
      tier: '5-Key',
      rate: 17.99,
      ltv: 140,
      maxDsr: 50,
      minIncome: 1800,
      reserve: 750,
      fee: 799,
      negativeEquityLimit: 5000,
    },
  },
  Santander: {
    'Tier8': {
      lender: 'Santander',
      tier: 'Tier8',
      rate: 11.49,
      ltv: 165,
      maxDsr: 30,
      minIncome: 2500,
      reserve: 600,
      fee: 0,
      negativeEquityLimit: 5000,
    },
    'Tier7': {
      lender: 'Santander',
      tier: 'Tier7',
      rate: 13.49,
      ltv: 165,
      maxDsr: 30,
      minIncome: 2500,
      reserve: 600,
      fee: 0,
      negativeEquityLimit: 5000,
    },
    'Tier6': {
      lender: 'Santander',
      tier: 'Tier6',
      rate: 16.49,
      ltv: 165,
      maxDsr: 30,
      minIncome: 2500,
      reserve: 550,
      fee: 0,
      negativeEquityLimit: 4000,
    },
    'Tier5': {
      lender: 'Santander',
      tier: 'Tier5',
      rate: 21.99,
      ltv: 165,
      maxDsr: 30,
      minIncome: 2500,
      reserve: 550,
      fee: 0,
      negativeEquityLimit: 3500,
    },
    'Tier4': {
      lender: 'Santander',
      tier: 'Tier4',
      rate: 24.49,
      ltv: 165,
      maxDsr: 30,
      minIncome: 2500,
      reserve: 550,
      fee: 0,
      negativeEquityLimit: 3500,
    },
    'Tier3': {
      lender: 'Santander',
      tier: 'Tier3',
      rate: 26.24,
      ltv: 165,
      maxDsr: 30,
      minIncome: 2500,
      reserve: 525,
      fee: 0,
      negativeEquityLimit: 3000,
    },
    'Tier2': {
      lender: 'Santander',
      tier: 'Tier2',
      rate: 29.99,
      ltv: 165,
      maxDsr: 30,
      minIncome: 2500,
      reserve: 750,
      fee: 0,
      negativeEquityLimit: 3000,
    },
    'Tier1': {
      lender: 'Santander',
      tier: 'Tier1',
      rate: 31.9,
      ltv: 165,
      maxDsr: 30,
      minIncome: 2500,
      reserve: 500,
      fee: 0,
      negativeEquityLimit: 3000,
    },
  },
  SDA: {
    'Star7': {
      lender: 'SDA',
      tier: 'Star7',
      rate: 11.99,
      ltv: 180,
      maxDsr: 65,
      minIncome: 1750,
      reserve: 600,
      fee: 399,
      negativeEquityLimit: 5000,
      rateUpsell: 2,
    },
    'Star6': {
      lender: 'SDA',
      tier: 'Star6',
      rate: 13.49,
      ltv: 180,
      maxDsr: 60,
      minIncome: 1750,
      reserve: 600,
      fee: 699,
      negativeEquityLimit: 5000,
      rateUpsell: 2,
    },
    'Star5': {
      lender: 'SDA',
      tier: 'Star5',
      rate: 14.49,
      ltv: 160,
      maxDsr: 55,
      minIncome: 1750,
      reserve: 500,
      fee: 699,
      negativeEquityLimit: 5000,
      rateUpsell: 2,
    },
    'Star4': {
      lender: 'SDA',
      tier: 'Star4',
      rate: 18.49,
      ltv: 150,
      maxDsr: 55,
      minIncome: 1750,
      reserve: 300,
      fee: 699,
      negativeEquityLimit: 4000,
      rateUpsell: 2,
    },
    'Star3': {
      lender: 'SDA',
      tier: 'Star3',
      rate: 21.99,
      ltv: 140,
      maxDsr: 45,
      minIncome: 1750,
      reserve: 400,
      fee: 699,
      negativeEquityLimit: 4000,
      rateUpsell: 2,
    },
    'Star2': {
      lender: 'SDA',
      tier: 'Star2',
      rate: 27.99,
      ltv: 140,
      maxDsr: 45,
      minIncome: 1750,
      reserve: 300,
      fee: 799,
      negativeEquityLimit: 3000,
      rateUpsell: 2,
    },
    'Star1': {
      lender: 'SDA',
      tier: 'Star1',
      rate: 29.99,
      ltv: 140,
      maxDsr: 45,
      minIncome: 1750,
      reserve: 100,
      fee: 799,
      negativeEquityLimit: 3000,
      rateUpsell: 2,
    },
    'StartRight': {
      lender: 'SDA',
      tier: 'StartRight',
      rate: 15.49,
      ltv: 140,
      maxDsr: 65,
      minIncome: 1750,
      reserve: 300,
      fee: 599,
      negativeEquityLimit: 5000,
      rateUpsell: 2,
    },
  },
};

export function getLenderProgram(lender: LenderType, tier: string): LenderProgram | null {
  return LENDER_PROGRAMS[lender]?.[tier] || null;
}

export function getLenderTiers(lender: LenderType): string[] {
  return Object.keys(LENDER_PROGRAMS[lender] || {});
}

export function getAllLenderPrograms(): Record<string, Record<string, LenderProgram>> {
  return LENDER_PROGRAMS;
}

export function getBaseReserve(program: LenderProgram): number {
  return program.reserve;
}
